/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_ronalzuniga;

/**
 *
 * @author Josué Zuniga
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearp = new javax.swing.JDialog();
        jd_addc = new javax.swing.JDialog();
        jd_modifyp = new javax.swing.JDialog();
        jd_aggc = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_artista = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_album = new javax.swing.JTextField();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jSpinner1 = new javax.swing.JSpinner();
        bt_aggc = new javax.swing.JButton();
        jd_modc = new javax.swing.JDialog();
        jd_deletec = new javax.swing.JDialog();
        jd_deletep = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_cp = new javax.swing.JMenuItem();
        jmi_acp = new javax.swing.JMenuItem();
        jmi_mp = new javax.swing.JMenuItem();
        jmi_delp = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_ac = new javax.swing.JMenuItem();
        jmi_mc = new javax.swing.JMenuItem();
        jmi_delc = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmi_of = new javax.swing.JMenuItem();
        jmi_save = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jd_crearpLayout = new javax.swing.GroupLayout(jd_crearp.getContentPane());
        jd_crearp.getContentPane().setLayout(jd_crearpLayout);
        jd_crearpLayout.setHorizontalGroup(
            jd_crearpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_crearpLayout.setVerticalGroup(
            jd_crearpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_addcLayout = new javax.swing.GroupLayout(jd_addc.getContentPane());
        jd_addc.getContentPane().setLayout(jd_addcLayout);
        jd_addcLayout.setHorizontalGroup(
            jd_addcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_addcLayout.setVerticalGroup(
            jd_addcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_modifypLayout = new javax.swing.GroupLayout(jd_modifyp.getContentPane());
        jd_modifyp.getContentPane().setLayout(jd_modifypLayout);
        jd_modifypLayout.setHorizontalGroup(
            jd_modifypLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_modifypLayout.setVerticalGroup(
            jd_modifypLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Agregar Canciones");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Puntuación");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Año");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("Álbum");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Artista");

        tf_artista.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        tf_nombre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        tf_album.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jYearChooser1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        bt_aggc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_aggc.setText("Agregar Canción");

        javax.swing.GroupLayout jd_aggcLayout = new javax.swing.GroupLayout(jd_aggc.getContentPane());
        jd_aggc.getContentPane().setLayout(jd_aggcLayout);
        jd_aggcLayout.setHorizontalGroup(
            jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_aggcLayout.createSequentialGroup()
                .addGroup(jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_aggcLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_aggcLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addGroup(jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_aggcLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_artista)
                                        .addComponent(tf_album, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))))))
                    .addGroup(jd_aggcLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(bt_aggc)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_aggcLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(148, 148, 148))
        );
        jd_aggcLayout.setVerticalGroup(
            jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_aggcLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGroup(jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_aggcLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_aggcLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_aggcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_album, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(bt_aggc)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_modcLayout = new javax.swing.GroupLayout(jd_modc.getContentPane());
        jd_modc.getContentPane().setLayout(jd_modcLayout);
        jd_modcLayout.setHorizontalGroup(
            jd_modcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_modcLayout.setVerticalGroup(
            jd_modcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_deletecLayout = new javax.swing.GroupLayout(jd_deletec.getContentPane());
        jd_deletec.getContentPane().setLayout(jd_deletecLayout);
        jd_deletecLayout.setHorizontalGroup(
            jd_deletecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_deletecLayout.setVerticalGroup(
            jd_deletecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_deletepLayout = new javax.swing.GroupLayout(jd_deletep.getContentPane());
        jd_deletep.getContentPane().setLayout(jd_deletepLayout);
        jd_deletepLayout.setHorizontalGroup(
            jd_deletepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_deletepLayout.setVerticalGroup(
            jd_deletepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setForeground(new java.awt.Color(51, 51, 255));
        jMenu1.setText("PlayList                 ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jmi_cp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmi_cp.setText("Crear PlayList");
        jmi_cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cpActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_cp);

        jmi_acp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmi_acp.setText("Agregar Canciones a PlayList");
        jMenu1.add(jmi_acp);

        jmi_mp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmi_mp.setText("Modificar PlayList");
        jMenu1.add(jmi_mp);

        jmi_delp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmi_delp.setText("Eliminar PlayList/Canciones");
        jMenu1.add(jmi_delp);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(51, 51, 255));
        jMenu2.setText("Canciones                ");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jmi_ac.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmi_ac.setText("Agregar Canciones");
        jMenu2.add(jmi_ac);

        jmi_mc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmi_mc.setText("Modificar Canciones");
        jMenu2.add(jmi_mc);

        jmi_delc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmi_delc.setText("Eliminar Canciones");
        jMenu2.add(jmi_delc);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(51, 51, 255));
        jMenu3.setText("Archivos");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jmi_of.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmi_of.setText("Abrir Archivo");
        jMenu3.add(jmi_of);

        jmi_save.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmi_save.setText("Guardar");
        jMenu3.add(jmi_save);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1044, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_cpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_aggc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSpinner jSpinner1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JDialog jd_addc;
    private javax.swing.JDialog jd_aggc;
    private javax.swing.JDialog jd_crearp;
    private javax.swing.JDialog jd_deletec;
    private javax.swing.JDialog jd_deletep;
    private javax.swing.JDialog jd_modc;
    private javax.swing.JDialog jd_modifyp;
    private javax.swing.JMenuItem jmi_ac;
    private javax.swing.JMenuItem jmi_acp;
    private javax.swing.JMenuItem jmi_cp;
    private javax.swing.JMenuItem jmi_delc;
    private javax.swing.JMenuItem jmi_delp;
    private javax.swing.JMenuItem jmi_mc;
    private javax.swing.JMenuItem jmi_mp;
    private javax.swing.JMenuItem jmi_of;
    private javax.swing.JMenuItem jmi_save;
    private javax.swing.JTextField tf_album;
    private javax.swing.JTextField tf_artista;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables
}
